# Generated by Django 3.0.7 on 2020-06-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wisestudy_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default=['a', 'b', 'c', 'd', 'e', 'f'], max_length=50),
        ),
    ]
