# Generated by Django 3.0.7 on 2020-06-20 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wisestudy_app', '0002_auto_20200621_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='a', max_length=50),
        ),
    ]
