# Generated by Django 3.0.7 on 2020-06-20 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wisestudy_app', '0004_auto_20200621_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
