# Generated by Django 3.0.7 on 2020-06-21 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wisestudy_app', '0005_auto_20200621_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='test', max_length=50),
        ),
    ]
